// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten.

const awsmobile = {
    aws_project_region: 'eu-central-1',
    aws_cognito_identity_pool_id: 'eu-west-2:c17fba56-3084-4079-8bab-f301a8f67b43',
    aws_cognito_region: 'eu-west-2',
    aws_user_pools_id: 'eu-west-2_jAsigE8EN',
    aws_user_pools_web_client_id: '1kbtspn0lg6g4n0p8nl22bkf2v',
    oauth: {},
  };
  
  
  export default awsmobile;